server:
#  All the request will travel through this port
  port: 9191
spring:
  application:
    name: API-GATEWAY

#    Directing every endpoint to its specific microservices
  cloud:
    gateway:
      routes:
#        - routes to user service
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

#          routes to department service
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
